"""1

Revision ID: 6fe5570724f7
Revises: 
Create Date: 2020-12-03 16:14:34.122411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fe5570724f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_room_id'), 'chat_room', ['id'], unique=False)
    op.create_table('new_chat_count',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user', postgresql.UUID(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_index(op.f('ix_new_chat_count_id'), 'new_chat_count', ['id'], unique=False)
    op.create_table('chat_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('chat_room_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('access', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_users_id'), 'chat_users', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('chat_room_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('sender', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('received', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_users_id'), table_name='chat_users')
    op.drop_table('chat_users')
    op.drop_index(op.f('ix_new_chat_count_id'), table_name='new_chat_count')
    op.drop_table('new_chat_count')
    op.drop_index(op.f('ix_chat_room_id'), table_name='chat_room')
    op.drop_table('chat_room')
    # ### end Alembic commands ###
